spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: 
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                ddl-auto: update
                format_sql: true
        show-sql: true